export enum OrderStage{
    PENDING_CONFIRMATION="PENDING_CONFIRMATION",
    PENDING_PAYMENT="PENDING_PAYMENT",
    PAYMENT_FAILED="PAYMENT_FAILED",
    PENDING_UPLOAD="PENDING_UPLOAD",
    UPLOADED="UPLOADED",
    DELIVERED="DELIVERED",
    CANCELLED="CANCELLED" 
}